links = [
{"source": "basil", "target": "cucumber", "direction": "u"},
{"source": "basil", "target": "tomato", "direction": "u"},
{"source": "bush beans", "target": "corn", "direction": "u"},
{"source": "bush beans", "target": "cucumber", "direction": "u"},
{"source": "bush beans", "target": "garlic", "direction": "d"},
{"source": "bush beans", "target": "marjoram", "direction": "u"},
{"source": "bush beans", "target": "strawberry", "direction": "u"},
{"source": "marigold", "target": "apple", "direction": "u"},
{"source": "garlic", "target": "apple", "direction": "u"},
{"source": "nasturtiums", "target": "apple", "direction": "u"},
{"source": "yarrow", "target": "apple", "direction": "u"},
{"source": "coriander", "target": "carrots", "direction": "u"},
{"source": "cucumber", "target": "carrots", "direction": "u"},
{"source": "dill", "target": "carrots", "direction": "u"},
{"source": "lettuce", "target": "carrots", "direction": "u"},
{"source": "marjoram", "target": "carrots", "direction": "u"},
{"source": "tomato", "target": "carrots", "direction": "u"},
{"source": "dill", "target": "coriander", "direction": "u"},
{"source": "cucumber", "target": "corn", "direction": "u"},
{"source": "marjoram", "target": "corn", "direction": "u"},
{"source": "zucchini", "target": "corn", "direction": "u"},
{"source": "dill", "target": "cucumber", "direction": "u"},
{"source": "lettuce", "target": "cucumber", "direction": "u"},
{"source": "marjoram", "target": "cucumber", "direction": "u"},
{"source": "nasturtiums", "target": "cucumber", "direction": "u"},
{"source": "carrots", "target": "marigold", "direction": "u"},
{"source": "lettuce", "target": "marigold", "direction": "u"},
{"source": "raspberry", "target": "marigold", "direction": "u"},
{"source": "strawberry", "target": "marigold", "direction": "u"},
{"source": "tomato", "target": "marigold", "direction": "u"},
{"source": "marjoram", "target": "lettuce", "direction": "u"},
{"source": "strawberry", "target": "lettuce", "direction": "u"},
{"source": "tomato", "target": "marjoram", "direction": "u"},
{"source": "zucchini", "target": "marjoram", "direction": "u"},
{"source": "tomato", "target": "nasturtiums", "direction": "u"},
{"source": "zucchini", "target": "nasturtiums", "direction": "u"},
{"source": "carrots", "target": "peas", "direction": "u"},
{"source": "corn", "target": "peas", "direction": "u"},
{"source": "cucumber", "target": "peas", "direction": "u"},
{"source": "garlic", "target": "peas", "direction": "d"},
{"source": "lettuce", "target": "peas", "direction": "u"},
{"source": "marjoram", "target": "peas", "direction": "u"},
{"source": "raspberry", "target": "peas", "direction": "u"},
{"source": "garlic", "target": "strawberry", "direction": "d"},
{"source": "dill", "target": "tomato", "direction": "u"}
];