links = [
{"source": "apricot", "target": "basil", "direction": "u"},
{"source": "apricot", "target": "marigold", "direction": "u"},
{"source": "apricot", "target": "garlic", "direction": "u"},
{"source": "apricot", "target": "nasturtiums", "direction": "u"},
{"source": "apricot", "target": "spinach", "direction": "u"},
{"source": "apricot", "target": "sunflower", "direction": "u"},
{"source": "apricot", "target": "tomato", "direction": "d"},
{"source": "apricot", "target": "yarrow", "direction": "u"},
{"source": "asparagus", "target": "basil", "direction": "u"},
{"source": "asparagus", "target": "marjoram", "direction": "u"},
{"source": "asparagus", "target": "parsley", "direction": "u"},
{"source": "asparagus", "target": "tomato", "direction": "u"},
{"source": "basil", "target": "chives", "direction": "u"},
{"source": "basil", "target": "cucumber", "direction": "u"},
{"source": "basil", "target": "fennel", "direction": "u"},
{"source": "basil", "target": "rue", "direction": "d"},
{"source": "basil", "target": "silverbeet", "direction": "d"},
{"source": "basil", "target": "tomato", "direction": "u"},
{"source": "beans", "target": "broccoli", "direction": "u"},
{"source": "beans", "target": "brussel sprouts", "direction": "u"},
{"source": "beans", "target": "cabbage", "direction": "u"},
{"source": "beans", "target": "carrots", "direction": "u"},
{"source": "beans", "target": "cauliflower", "direction": "u"},
{"source": "beans", "target": "chives", "direction": "d"},
{"source": "beans", "target": "corn", "direction": "u"},
{"source": "beans", "target": "cucumber", "direction": "u"},
{"source": "beans", "target": "fennel", "direction": "d"},
{"source": "beans", "target": "marigold", "direction": "u"},
{"source": "beans", "target": "garlic", "direction": "d"},
{"source": "beans", "target": "grape vine", "direction": "u"},
{"source": "beans", "target": "lettuce", "direction": "u"},
{"source": "beans", "target": "marjoram", "direction": "u"},
{"source": "beans", "target": "onion", "direction": "d"},
{"source": "beans", "target": "parsley", "direction": "u"},
{"source": "beans", "target": "peas", "direction": "u"},
{"source": "beans", "target": "potato", "direction": "u"},
{"source": "beans", "target": "rosemary", "direction": "u"},
{"source": "beans", "target": "sage", "direction": "u"},
{"source": "beans", "target": "savory", "direction": "u"},
{"source": "broad beans", "target": "broccoli", "direction": "u"},
{"source": "broad beans", "target": "brussel sprouts", "direction": "u"},
{"source": "broad beans", "target": "cabbage", "direction": "u"},
{"source": "broad beans", "target": "cauliflower", "direction": "u"},
{"source": "broad beans", "target": "chives", "direction": "d"},
{"source": "broad beans", "target": "corn", "direction": "u"},
{"source": "broad beans", "target": "fennel", "direction": "d"},
{"source": "broad beans", "target": "garlic", "direction": "d"},
{"source": "broad beans", "target": "lettuce", "direction": "u"},
{"source": "broad beans", "target": "marjoram", "direction": "u"},
{"source": "broad beans", "target": "onion", "direction": "d"},
{"source": "broad beans", "target": "potato", "direction": "u"},
{"source": "broad beans", "target": "spinach", "direction": "u"},
{"source": "bush beans", "target": "beets", "direction": "u"},
{"source": "bush beans", "target": "broccoli", "direction": "u"},
{"source": "bush beans", "target": "brussel sprouts", "direction": "u"},
{"source": "bush beans", "target": "cabbage", "direction": "u"},
{"source": "bush beans", "target": "cauliflower", "direction": "u"},
{"source": "bush beans", "target": "celery", "direction": "u"},
{"source": "bush beans", "target": "chives", "direction": "d"},
{"source": "bush beans", "target": "corn", "direction": "u"},
{"source": "bush beans", "target": "cucumber", "direction": "u"},
{"source": "bush beans", "target": "garlic", "direction": "d"},
{"source": "bush beans", "target": "marjoram", "direction": "u"},
{"source": "bush beans", "target": "onion", "direction": "d"},
{"source": "bush beans", "target": "potato", "direction": "u"},
{"source": "bush beans", "target": "strawberry", "direction": "u"},
{"source": "bush beans", "target": "sunflower", "direction": "u"},
{"source": "climbing beans", "target": "beets", "direction": "d"},
{"source": "climbing beans", "target": "broccoli", "direction": "u"},
{"source": "climbing beans", "target": "brussel sprouts", "direction": "u"},
{"source": "climbing beans", "target": "cabbage", "direction": "u"},
{"source": "climbing beans", "target": "cauliflower", "direction": "u"},
{"source": "climbing beans", "target": "chives", "direction": "d"},
{"source": "climbing beans", "target": "corn", "direction": "u"},
{"source": "climbing beans", "target": "garlic", "direction": "d"},
{"source": "climbing beans", "target": "lettuce", "direction": "u"},
{"source": "climbing beans", "target": "marjoram", "direction": "u"},
{"source": "climbing beans", "target": "onion", "direction": "d"},
{"source": "climbing beans", "target": "radish", "direction": "u"},
{"source": "climbing beans", "target": "sunflower", "direction": "d"},
{"source": "chives", "target": "apple", "direction": "u"},
{"source": "marigold", "target": "apple", "direction": "u"},
{"source": "garlic", "target": "apple", "direction": "u"},
{"source": "grass", "target": "apple", "direction": "d"},
{"source": "horseradish", "target": "apple", "direction": "u"},
{"source": "lemon balm", "target": "apple", "direction": "u"},
{"source": "mustard", "target": "apple", "direction": "u"},
{"source": "nasturtiums", "target": "apple", "direction": "u"},
{"source": "potato", "target": "apple", "direction": "d"},
{"source": "spinach", "target": "apple", "direction": "u"},
{"source": "tansy", "target": "apple", "direction": "u"},
{"source": "yarrow", "target": "apple", "direction": "u"},
{"source": "grass", "target": "apricot", "direction": "d"},
{"source": "horseradish", "target": "apricot", "direction": "u"},
{"source": "lemon balm", "target": "apricot", "direction": "u"},
{"source": "mustard", "target": "apricot", "direction": "u"},
{"source": "tansy", "target": "apricot", "direction": "u"},
{"source": "chives", "target": "asparagus", "direction": "u"},
{"source": "eggplant", "target": "beans", "direction": "u"},
{"source": "parsnip", "target": "beans", "direction": "u"},
{"source": "shallots", "target": "beans", "direction": "d"},
{"source": "cabbage", "target": "beets", "direction": "u"},
{"source": "dill", "target": "beets", "direction": "u"},
{"source": "lettuce", "target": "beets", "direction": "u"},
{"source": "marjoram", "target": "beets", "direction": "u"},
{"source": "onion", "target": "beets", "direction": "u"},
{"source": "potato", "target": "beets", "direction": "u"},
{"source": "silverbeet", "target": "beets", "direction": "u"},
{"source": "tomato", "target": "beets", "direction": "u"},
{"source": "cabbage", "target": "borage", "direction": "u"},
{"source": "cucumber", "target": "borage", "direction": "u"},
{"source": "strawberry", "target": "borage", "direction": "u"},
{"source": "tansy", "target": "borage", "direction": "u"},
{"source": "tomato", "target": "borage", "direction": "u"},
{"source": "beets", "target": "broccoli", "direction": "u"},
{"source": "borage", "target": "broccoli", "direction": "u"},
{"source": "coriander", "target": "broccoli", "direction": "u"},
{"source": "cucumber", "target": "broccoli", "direction": "u"},
{"source": "dill", "target": "broccoli", "direction": "u"},
{"source": "marigold", "target": "broccoli", "direction": "u"},
{"source": "marjoram", "target": "broccoli", "direction": "u"},
{"source": "nasturtiums", "target": "broccoli", "direction": "u"},
{"source": "potato", "target": "broccoli", "direction": "u"},
{"source": "rue", "target": "broccoli", "direction": "d"},
{"source": "strawberry", "target": "broccoli", "direction": "d"},
{"source": "tomato", "target": "broccoli", "direction": "u"},
{"source": "beets", "target": "brussel sprouts", "direction": "u"},
{"source": "borage", "target": "brussel sprouts", "direction": "u"},
{"source": "coriander", "target": "brussel sprouts", "direction": "u"},
{"source": "cucumber", "target": "brussel sprouts", "direction": "u"},
{"source": "dill", "target": "brussel sprouts", "direction": "u"},
{"source": "marigold", "target": "brussel sprouts", "direction": "u"},
{"source": "marjoram", "target": "brussel sprouts", "direction": "u"},
{"source": "potato", "target": "brussel sprouts", "direction": "u"},
{"source": "strawberry", "target": "brussel sprouts", "direction": "u"},
{"source": "sunflower", "target": "brussel sprouts", "direction": "u"},
{"source": "celery", "target": "cabbage", "direction": "u"},
{"source": "coriander", "target": "cabbage", "direction": "u"},
{"source": "cucumber", "target": "cabbage", "direction": "u"},
{"source": "dill", "target": "cabbage", "direction": "u"},
{"source": "marigold", "target": "cabbage", "direction": "u"},
{"source": "garlic", "target": "cabbage", "direction": "d"},
{"source": "lavender", "target": "cabbage", "direction": "u"},
{"source": "lettuce", "target": "cabbage", "direction": "u"},
{"source": "marjoram", "target": "cabbage", "direction": "u"},
{"source": "mint", "target": "cabbage", "direction": "u"},
{"source": "nasturtiums", "target": "cabbage", "direction": "u"},
{"source": "onion", "target": "cabbage", "direction": "u"},
{"source": "potato", "target": "cabbage", "direction": "u"},
{"source": "rosemary", "target": "cabbage", "direction": "u"},
{"source": "rue", "target": "cabbage", "direction": "d"},
{"source": "sage", "target": "cabbage", "direction": "u"},
{"source": "strawberry", "target": "cabbage", "direction": "d"},
{"source": "tansy", "target": "cabbage", "direction": "u"},
{"source": "thyme", "target": "cabbage", "direction": "u"},
{"source": "cabbage", "target": "chamomile", "direction": "u"},
{"source": "mint", "target": "chamomile", "direction": "d"},
{"source": "chives", "target": "carrots", "direction": "u"},
{"source": "coriander", "target": "carrots", "direction": "u"},
{"source": "cucumber", "target": "carrots", "direction": "u"},
{"source": "dill", "target": "carrots", "direction": "u"},
{"source": "fruit trees", "target": "carrots", "direction": "u"},
{"source": "leeks", "target": "carrots", "direction": "u"},
{"source": "lettuce", "target": "carrots", "direction": "u"},
{"source": "marjoram", "target": "carrots", "direction": "u"},
{"source": "onion", "target": "carrots", "direction": "u"},
{"source": "parsnip", "target": "carrots", "direction": "d"},
{"source": "radish", "target": "carrots", "direction": "u"},
{"source": "rue", "target": "carrots", "direction": "u"},
{"source": "tomato", "target": "carrots", "direction": "u"},
{"source": "beets", "target": "cauliflower", "direction": "u"},
{"source": "borage", "target": "cauliflower", "direction": "u"},
{"source": "celery", "target": "cauliflower", "direction": "u"},
{"source": "coriander", "target": "cauliflower", "direction": "u"},
{"source": "cucumber", "target": "cauliflower", "direction": "u"},
{"source": "dill", "target": "cauliflower", "direction": "u"},
{"source": "marigold", "target": "cauliflower", "direction": "u"},
{"source": "marjoram", "target": "cauliflower", "direction": "u"},
{"source": "potato", "target": "cauliflower", "direction": "u"},
{"source": "rue", "target": "cauliflower", "direction": "d"},
{"source": "strawberry", "target": "cauliflower", "direction": "d"},
{"source": "tomato", "target": "cauliflower", "direction": "u"},
{"source": "dill", "target": "celery", "direction": "u"},
{"source": "leeks", "target": "celery", "direction": "u"},
{"source": "marjoram", "target": "celery", "direction": "u"},
{"source": "parsnip", "target": "celery", "direction": "d"},
{"source": "potato", "target": "celery", "direction": "d"},
{"source": "tomato", "target": "celery", "direction": "u"},
{"source": "chives", "target": "cherry", "direction": "u"},
{"source": "marigold", "target": "cherry", "direction": "u"},
{"source": "garlic", "target": "cherry", "direction": "u"},
{"source": "grass", "target": "cherry", "direction": "d"},
{"source": "horseradish", "target": "cherry", "direction": "u"},
{"source": "lemon balm", "target": "cherry", "direction": "u"},
{"source": "lettuce", "target": "cherry", "direction": "u"},
{"source": "mustard", "target": "cherry", "direction": "u"},
{"source": "nasturtiums", "target": "cherry", "direction": "u"},
{"source": "potato", "target": "cherry", "direction": "d"},
{"source": "silverbeet", "target": "cherry", "direction": "u"},
{"source": "spinach", "target": "cherry", "direction": "u"},
{"source": "tansy", "target": "cherry", "direction": "u"},
{"source": "yarrow", "target": "cherry", "direction": "u"},
{"source": "coriander", "target": "chervil", "direction": "u"},
{"source": "dill", "target": "chervil", "direction": "u"},
{"source": "lettuce", "target": "chervil", "direction": "u"},
{"source": "radish", "target": "chervil", "direction": "u"},
{"source": "fruit trees", "target": "chives", "direction": "u"},
{"source": "marjoram", "target": "chives", "direction": "u"},
{"source": "parsley", "target": "chives", "direction": "u"},
{"source": "parsnip", "target": "chives", "direction": "u"},
{"source": "roses", "target": "chives", "direction": "u"},
{"source": "strawberry", "target": "chives", "direction": "u"},
{"source": "tomato", "target": "chives", "direction": "u"},
{"source": "dill", "target": "coriander", "direction": "u"},
{"source": "parsnip", "target": "coriander", "direction": "u"},
{"source": "parsnip", "target": "dill", "direction": "u"},
{"source": "cucumber", "target": "corn", "direction": "u"},
{"source": "marjoram", "target": "corn", "direction": "u"},
{"source": "parsnip", "target": "corn", "direction": "u"},
{"source": "potato", "target": "corn", "direction": "u"},
{"source": "pumpkin", "target": "corn", "direction": "u"},
{"source": "radish", "target": "corn", "direction": "u"},
{"source": "zucchini", "target": "corn", "direction": "u"},
{"source": "dill", "target": "cucumber", "direction": "u"},
{"source": "lettuce", "target": "cucumber", "direction": "u"},
{"source": "marjoram", "target": "cucumber", "direction": "u"},
{"source": "nasturtiums", "target": "cucumber", "direction": "u"},
{"source": "potato", "target": "cucumber", "direction": "d"},
{"source": "radish", "target": "cucumber", "direction": "u"},
{"source": "sage", "target": "cucumber", "direction": "d"},
{"source": "sunflower", "target": "cucumber", "direction": "u"},
{"source": "tansy", "target": "cucumber", "direction": "u"},
{"source": "coriander", "target": "fennel", "direction": "d"},
{"source": "dill", "target": "fennel", "direction": "u"},
{"source": "lavender", "target": "fennel", "direction": "d"},
{"source": "tomato", "target": "fennel", "direction": "d"},
{"source": "carrots", "target": "marigold", "direction": "u"},
{"source": "fruit trees", "target": "marigold", "direction": "u"},
{"source": "lettuce", "target": "marigold", "direction": "u"},
{"source": "potato", "target": "marigold", "direction": "u"},
{"source": "raspberry", "target": "marigold", "direction": "u"},
{"source": "roses", "target": "marigold", "direction": "u"},
{"source": "strawberry", "target": "marigold", "direction": "u"},
{"source": "tomato", "target": "marigold", "direction": "u"},
{"source": "garlic", "target": "fruit trees", "direction": "u"},
{"source": "grass", "target": "fruit trees", "direction": "d"},
{"source": "lemon balm", "target": "fruit trees", "direction": "u"},
{"source": "mustard", "target": "fruit trees", "direction": "u"},
{"source": "nasturtiums", "target": "fruit trees", "direction": "u"},
{"source": "silverbeet", "target": "fruit trees", "direction": "u"},
{"source": "spinach", "target": "fruit trees", "direction": "u"},
{"source": "tansy", "target": "fruit trees", "direction": "u"},
{"source": "yarrow", "target": "fruit trees", "direction": "u"},
{"source": "chervil", "target": "garlic", "direction": "u"},
{"source": "lavender", "target": "garlic", "direction": "u"},
{"source": "rosemary", "target": "garlic", "direction": "u"},
{"source": "roses", "target": "garlic", "direction": "u"},
{"source": "sunflower", "target": "garlic", "direction": "d"},
{"source": "mustard", "target": "grape vine", "direction": "u"},
{"source": "tansy", "target": "grape vine", "direction": "u"},
{"source": "tomato", "target": "grape vine", "direction": "u"},
{"source": "yarrow", "target": "grape vine", "direction": "u"},
{"source": "marjoram", "target": "lettuce", "direction": "u"},
{"source": "onion", "target": "lettuce", "direction": "u"},
{"source": "parsley", "target": "lettuce", "direction": "d"},
{"source": "parsnip", "target": "lettuce", "direction": "u"},
{"source": "radish", "target": "lettuce", "direction": "u"},
{"source": "strawberry", "target": "lettuce", "direction": "u"},
{"source": "eggplant", "target": "marjoram", "direction": "u"},
{"source": "lavender", "target": "marjoram", "direction": "u"},
{"source": "leeks", "target": "marjoram", "direction": "u"},
{"source": "onion", "target": "marjoram", "direction": "u"},
{"source": "parsnip", "target": "marjoram", "direction": "u"},
{"source": "potato", "target": "marjoram", "direction": "u"},
{"source": "pumpkin", "target": "marjoram", "direction": "u"},
{"source": "radish", "target": "marjoram", "direction": "u"},
{"source": "shallots", "target": "marjoram", "direction": "u"},
{"source": "silverbeet", "target": "marjoram", "direction": "u"},
{"source": "spinach", "target": "marjoram", "direction": "u"},
{"source": "tomato", "target": "marjoram", "direction": "u"},
{"source": "zucchini", "target": "marjoram", "direction": "u"},
{"source": "chives", "target": "mulberry", "direction": "u"},
{"source": "marigold", "target": "mulberry", "direction": "u"},
{"source": "garlic", "target": "mulberry", "direction": "u"},
{"source": "grape vine", "target": "mulberry", "direction": "u"},
{"source": "grass", "target": "mulberry", "direction": "u"},
{"source": "lemon balm", "target": "mulberry", "direction": "u"},
{"source": "mustard", "target": "mulberry", "direction": "u"},
{"source": "nasturtiums", "target": "mulberry", "direction": "u"},
{"source": "silverbeet", "target": "mulberry", "direction": "u"},
{"source": "spinach", "target": "mulberry", "direction": "u"},
{"source": "tansy", "target": "mulberry", "direction": "u"},
{"source": "yarrow", "target": "mulberry", "direction": "u"},
{"source": "potato", "target": "nasturtiums", "direction": "u"},
{"source": "radish", "target": "nasturtiums", "direction": "u"},
{"source": "roses", "target": "nasturtiums", "direction": "u"},
{"source": "tomato", "target": "nasturtiums", "direction": "u"},
{"source": "zucchini", "target": "nasturtiums", "direction": "u"},
{"source": "leeks", "target": "onion", "direction": "u"},
{"source": "parsley", "target": "onion", "direction": "u"},
{"source": "parsnip", "target": "onion", "direction": "u"},
{"source": "roses", "target": "onion", "direction": "u"},
{"source": "silverbeet", "target": "onion", "direction": "u"},
{"source": "strawberry", "target": "onion", "direction": "u"},
{"source": "tomato", "target": "onion", "direction": "u"},
{"source": "chervil", "target": "parsley", "direction": "u"},
{"source": "mint", "target": "parsley", "direction": "d"},
{"source": "roses", "target": "parsley", "direction": "u"},
{"source": "tomato", "target": "parsley", "direction": "u"},
{"source": "borage", "target": "peas", "direction": "u"},
{"source": "cabbage", "target": "peas", "direction": "u"},
{"source": "carrots", "target": "peas", "direction": "u"},
{"source": "celery", "target": "peas", "direction": "u"},
{"source": "chives", "target": "peas", "direction": "d"},
{"source": "corn", "target": "peas", "direction": "u"},
{"source": "cucumber", "target": "peas", "direction": "u"},
{"source": "garlic", "target": "peas", "direction": "d"},
{"source": "lettuce", "target": "peas", "direction": "u"},
{"source": "marjoram", "target": "peas", "direction": "u"},
{"source": "onion", "target": "peas", "direction": "d"},
{"source": "parsnip", "target": "peas", "direction": "u"},
{"source": "potato", "target": "peas", "direction": "u"},
{"source": "raspberry", "target": "peas", "direction": "u"},
{"source": "sage", "target": "peas", "direction": "u"},
{"source": "shallots", "target": "peas", "direction": "d"},
{"source": "cabbage", "target": "pennyroyal", "direction": "u"},
{"source": "eggplant", "target": "potato", "direction": "u"},
{"source": "horseradish", "target": "potato", "direction": "u"},
{"source": "parsnip", "target": "potato", "direction": "u"},
{"source": "pumpkin", "target": "potato", "direction": "d"},
{"source": "raspberry", "target": "potato", "direction": "d"},
{"source": "rosemary", "target": "potato", "direction": "d"},
{"source": "sunflower", "target": "potato", "direction": "d"},
{"source": "tomato", "target": "potato", "direction": "d"},
{"source": "parsnip", "target": "radish", "direction": "u"},
{"source": "carrots", "target": "rosemary", "direction": "u"},
{"source": "parsley", "target": "rosemary", "direction": "u"},
{"source": "sage", "target": "rosemary", "direction": "u"},
{"source": "tomato", "target": "rosemary", "direction": "d"},
{"source": "horseradish", "target": "roses", "direction": "u"},
{"source": "lavender", "target": "roses", "direction": "u"},
{"source": "lemon balm", "target": "roses", "direction": "u"},
{"source": "rue", "target": "roses", "direction": "u"},
{"source": "sage", "target": "roses", "direction": "u"},
{"source": "tansy", "target": "roses", "direction": "u"},
{"source": "thyme", "target": "roses", "direction": "u"},
{"source": "raspberry", "target": "rue", "direction": "u"},
{"source": "sage", "target": "rue", "direction": "d"},
{"source": "carrots", "target": "sage", "direction": "u"},
{"source": "grass", "target": "sage", "direction": "d"},
{"source": "parsnip", "target": "sage", "direction": "u"},
{"source": "strawberry", "target": "sage", "direction": "u"},
{"source": "onion", "target": "savory", "direction": "u"},
{"source": "lavender", "target": "silverbeet", "direction": "u"},
{"source": "strawberry", "target": "spinach", "direction": "u"},
{"source": "borage", "target": "squash", "direction": "u"},
{"source": "corn", "target": "squash", "direction": "u"},
{"source": "marjoram", "target": "squash", "direction": "u"},
{"source": "nasturtiums", "target": "squash", "direction": "u"},
{"source": "sunflower", "target": "squash", "direction": "u"},
{"source": "tansy", "target": "squash", "direction": "u"},
{"source": "garlic", "target": "strawberry", "direction": "d"},
{"source": "lavender", "target": "strawberry", "direction": "u"},
{"source": "cabbage", "target": "tomato", "direction": "d"},
{"source": "dill", "target": "tomato", "direction": "u"},
{"source": "gooseberry", "target": "tomato", "direction": "u"},
{"source": "mint", "target": "tomato", "direction": "u"},
{"source": "parsnip", "target": "tomato", "direction": "u"},
{"source": "chervil", "target": "yarrow", "direction": "u"},
{"source": "grass", "target": "yarrow", "direction": "u"},
{"source": "tansy", "target": "yarrow", "direction": "u"}
];