links = [
{"source": "basil", "target": "chives", "direction": "u"},
{"source": "basil", "target": "cucumber", "direction": "u"},
{"source": "basil", "target": "tomato", "direction": "u"},
{"source": "bush beans", "target": "chives", "direction": "d"},
{"source": "bush beans", "target": "corn", "direction": "u"},
{"source": "bush beans", "target": "cucumber", "direction": "u"},
{"source": "bush beans", "target": "garlic", "direction": "d"},
{"source": "bush beans", "target": "marjoram", "direction": "u"},
{"source": "bush beans", "target": "onion", "direction": "d"},
{"source": "bush beans", "target": "strawberry", "direction": "u"},
{"source": "bush beans", "target": "sunflower", "direction": "u"},
{"source": "chives", "target": "apple", "direction": "u"},
{"source": "marigold", "target": "apple", "direction": "u"},
{"source": "garlic", "target": "apple", "direction": "u"},
{"source": "grass", "target": "apple", "direction": "d"},
{"source": "nasturtiums", "target": "apple", "direction": "u"},
{"source": "spinach", "target": "apple", "direction": "u"},
{"source": "yarrow", "target": "apple", "direction": "u"},
{"source": "chives", "target": "carrots", "direction": "u"},
{"source": "coriander", "target": "carrots", "direction": "u"},
{"source": "cucumber", "target": "carrots", "direction": "u"},
{"source": "dill", "target": "carrots", "direction": "u"},
{"source": "fruit trees", "target": "carrots", "direction": "u"},
{"source": "lettuce", "target": "carrots", "direction": "u"},
{"source": "marjoram", "target": "carrots", "direction": "u"},
{"source": "onion", "target": "carrots", "direction": "u"},
{"source": "parsnip", "target": "carrots", "direction": "d"},
{"source": "tomato", "target": "carrots", "direction": "u"},
{"source": "fruit trees", "target": "chives", "direction": "u"},
{"source": "marjoram", "target": "chives", "direction": "u"},
{"source": "parsley", "target": "chives", "direction": "u"},
{"source": "parsnip", "target": "chives", "direction": "u"},
{"source": "strawberry", "target": "chives", "direction": "u"},
{"source": "tomato", "target": "chives", "direction": "u"},
{"source": "dill", "target": "coriander", "direction": "u"},
{"source": "parsnip", "target": "coriander", "direction": "u"},
{"source": "parsnip", "target": "dill", "direction": "u"},
{"source": "cucumber", "target": "corn", "direction": "u"},
{"source": "marjoram", "target": "corn", "direction": "u"},
{"source": "parsnip", "target": "corn", "direction": "u"},
{"source": "pumpkin", "target": "corn", "direction": "u"},
{"source": "zucchini", "target": "corn", "direction": "u"},
{"source": "dill", "target": "cucumber", "direction": "u"},
{"source": "lettuce", "target": "cucumber", "direction": "u"},
{"source": "marjoram", "target": "cucumber", "direction": "u"},
{"source": "nasturtiums", "target": "cucumber", "direction": "u"},
{"source": "sunflower", "target": "cucumber", "direction": "u"},
{"source": "carrots", "target": "marigold", "direction": "u"},
{"source": "fruit trees", "target": "marigold", "direction": "u"},
{"source": "lettuce", "target": "marigold", "direction": "u"},
{"source": "raspberry", "target": "marigold", "direction": "u"},
{"source": "strawberry", "target": "marigold", "direction": "u"},
{"source": "tomato", "target": "marigold", "direction": "u"},
{"source": "garlic", "target": "fruit trees", "direction": "u"},
{"source": "grass", "target": "fruit trees", "direction": "d"},
{"source": "nasturtiums", "target": "fruit trees", "direction": "u"},
{"source": "spinach", "target": "fruit trees", "direction": "u"},
{"source": "yarrow", "target": "fruit trees", "direction": "u"},
{"source": "rosemary", "target": "garlic", "direction": "u"},
{"source": "sunflower", "target": "garlic", "direction": "d"},
{"source": "tomato", "target": "grape vine", "direction": "u"},
{"source": "yarrow", "target": "grape vine", "direction": "u"},
{"source": "marjoram", "target": "lettuce", "direction": "u"},
{"source": "onion", "target": "lettuce", "direction": "u"},
{"source": "parsley", "target": "lettuce", "direction": "d"},
{"source": "parsnip", "target": "lettuce", "direction": "u"},
{"source": "strawberry", "target": "lettuce", "direction": "u"},
{"source": "onion", "target": "marjoram", "direction": "u"},
{"source": "parsnip", "target": "marjoram", "direction": "u"},
{"source": "pumpkin", "target": "marjoram", "direction": "u"},
{"source": "shallots", "target": "marjoram", "direction": "u"},
{"source": "spinach", "target": "marjoram", "direction": "u"},
{"source": "tomato", "target": "marjoram", "direction": "u"},
{"source": "zucchini", "target": "marjoram", "direction": "u"},
{"source": "tomato", "target": "nasturtiums", "direction": "u"},
{"source": "zucchini", "target": "nasturtiums", "direction": "u"},
{"source": "parsley", "target": "onion", "direction": "u"},
{"source": "parsnip", "target": "onion", "direction": "u"},
{"source": "strawberry", "target": "onion", "direction": "u"},
{"source": "tomato", "target": "onion", "direction": "u"},
{"source": "mint", "target": "parsley", "direction": "d"},
{"source": "tomato", "target": "parsley", "direction": "u"},
{"source": "carrots", "target": "peas", "direction": "u"},
{"source": "chives", "target": "peas", "direction": "d"},
{"source": "corn", "target": "peas", "direction": "u"},
{"source": "cucumber", "target": "peas", "direction": "u"},
{"source": "garlic", "target": "peas", "direction": "d"},
{"source": "lettuce", "target": "peas", "direction": "u"},
{"source": "marjoram", "target": "peas", "direction": "u"},
{"source": "onion", "target": "peas", "direction": "d"},
{"source": "parsnip", "target": "peas", "direction": "u"},
{"source": "raspberry", "target": "peas", "direction": "u"},
{"source": "shallots", "target": "peas", "direction": "d"},
{"source": "carrots", "target": "rosemary", "direction": "u"},
{"source": "parsley", "target": "rosemary", "direction": "u"},
{"source": "tomato", "target": "rosemary", "direction": "d"},
{"source": "strawberry", "target": "spinach", "direction": "u"},
{"source": "garlic", "target": "strawberry", "direction": "d"},
{"source": "dill", "target": "tomato", "direction": "u"},
{"source": "mint", "target": "tomato", "direction": "u"},
{"source": "parsnip", "target": "tomato", "direction": "u"},
{"source": "grass", "target": "yarrow", "direction": "u"}
];