nodes = {
"apple": {"name": "apple", "size": 4},
"basil": {"name": "basil", "size": 2},
"bush beans": {"name": "bush beans", "size": 5},
"carrots": {"name": "carrots", "size": 8},
"coriander": {"name": "coriander", "size": 2},
"corn": {"name": "corn", "size": 5},
"cucumber": {"name": "cucumber", "size": 9},
"dill": {"name": "dill", "size": 4},
"garlic": {"name": "garlic", "size": 4},
"lettuce": {"name": "lettuce", "size": 6},
"marigold": {"name": "marigold", "size": 6},
"marjoram": {"name": "marjoram", "size": 8},
"nasturtiums": {"name": "nasturtiums", "size": 4},
"peas": {"name": "peas", "size": 7},
"raspberry": {"name": "raspberry", "size": 2},
"strawberry": {"name": "strawberry", "size": 4},
"tomato": {"name": "tomato", "size": 6},
"yarrow": {"name": "yarrow", "size": 1},
"zucchini": {"name": "zucchini", "size": 3}
};