nodes = {
"apple": {"name": "apple", "size": 12},
"apricot": {"name": "apricot", "size": 13},
"asparagus": {"name": "asparagus", "size": 5},
"basil": {"name": "basil", "size": 8},
"beans": {"name": "beans", "size": 24},
"beets": {"name": "beets", "size": 13},
"borage": {"name": "borage", "size": 10},
"broad beans": {"name": "broad beans", "size": 13},
"broccoli": {"name": "broccoli", "size": 16},
"brussel sprouts": {"name": "brussel sprouts", "size": 14},
"bush beans": {"name": "bush beans", "size": 15},
"cabbage": {"name": "cabbage", "size": 29},
"carrots": {"name": "carrots", "size": 18},
"cauliflower": {"name": "cauliflower", "size": 16},
"celery": {"name": "celery", "size": 10},
"chamomile": {"name": "chamomile", "size": 2},
"cherry": {"name": "cherry", "size": 14},
"chervil": {"name": "chervil", "size": 7},
"chives": {"name": "chives", "size": 18},
"climbing beans": {"name": "climbing beans", "size": 13},
"coriander": {"name": "coriander", "size": 9},
"corn": {"name": "corn", "size": 13},
"cucumber": {"name": "cucumber", "size": 20},
"dill": {"name": "dill", "size": 13},
"eggplant": {"name": "eggplant", "size": 3},
"fennel": {"name": "fennel", "size": 7},
"fruit trees": {"name": "fruit trees", "size": 12},
"garlic": {"name": "garlic", "size": 17},
"gooseberry": {"name": "gooseberry", "size": 1},
"grape vine": {"name": "grape vine", "size": 6},
"grass": {"name": "grass", "size": 7},
"horseradish": {"name": "horseradish", "size": 5},
"lavender": {"name": "lavender", "size": 7},
"leeks": {"name": "leeks", "size": 4},
"lemon balm": {"name": "lemon balm", "size": 6},
"lettuce": {"name": "lettuce", "size": 17},
"marigold": {"name": "marigold", "size": 17},
"marjoram": {"name": "marjoram", "size": 31},
"mint": {"name": "mint", "size": 4},
"mulberry": {"name": "mulberry", "size": 12},
"mustard": {"name": "mustard", "size": 6},
"nasturtiums": {"name": "nasturtiums", "size": 14},
"onion": {"name": "onion", "size": 18},
"parsley": {"name": "parsley", "size": 10},
"parsnip": {"name": "parsnip", "size": 15},
"peas": {"name": "peas", "size": 17},
"pennyroyal": {"name": "pennyroyal", "size": 1},
"potato": {"name": "potato", "size": 25},
"pumpkin": {"name": "pumpkin", "size": 3},
"radish": {"name": "radish", "size": 9},
"raspberry": {"name": "raspberry", "size": 4},
"rosemary": {"name": "rosemary", "size": 8},
"roses": {"name": "roses", "size": 13},
"rue": {"name": "rue", "size": 8},
"sage": {"name": "sage", "size": 11},
"savory": {"name": "savory", "size": 2},
"shallots": {"name": "shallots", "size": 3},
"silverbeet": {"name": "silverbeet", "size": 8},
"spinach": {"name": "spinach", "size": 8},
"squash": {"name": "squash", "size": 6},
"strawberry": {"name": "strawberry", "size": 14},
"sunflower": {"name": "sunflower", "size": 8},
"tansy": {"name": "tansy", "size": 12},
"thyme": {"name": "thyme", "size": 2},
"tomato": {"name": "tomato", "size": 24},
"yarrow": {"name": "yarrow", "size": 9},
"zucchini": {"name": "zucchini", "size": 3}
};